### ISSUE TITLE
Question about the binary file of IWR6843AOPEVM

### ISSUE THREAD

**Issue by EvA56356** [pfeghali/pymmWave#4]
The sensor is able to connect to the demo visualizer but failed to connect to this programme.
What binary file should the sensor be flashed with?
The error report is like this:
![image](https://user-images.githubusercontent.com/111786705/200377697-92f097d5-8239-4941-9191-a39fc9dcaaaf.png)

**Comment by Thalerpe** [comment]
For me it was a problem within the configuration, where the reading was too slow and the writing then infered with it. A little bit of waiting solved the issue for me.

**Comment by pfeghali** [comment]
That's great to hear!
